FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir streamlit plotly pandas boto3 pyarrow

COPY dashboard/ ./dashboard/
COPY etl/minio_utils.py ./etl/minio_utils.py

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]
